### ISSUE TITLE
Question on the Glamourer's link part

### ISSUE THREAD

**Issue by dwnenr** [ViviAshe/XIVSnapper#6]
Is anyone able to walk me through on what needs to be done? I cant find any resources online so I'm completely lost after 

1. Saving a snapshot of a player
2. exporting their snapshot as PMP (not sure if this is required)
3. Saved their design on glamourer

I saw ViviAshe mentioning that the Glamourer's API does not provide the target's design code so I need to manually copy it. But I'm not sure what I need to copy it, where to copy it from and what to do with it.

Thanks in advance.

**Comment by Lucsmat** [comment]
> Is anyone able to walk me through on what needs to be done? I cant find any resources online so I'm completely lost after
> 
> 1. Saving a snapshot of a player
> 2. exporting their snapshot as PMP (not sure if this is required)
> 3. Saved their design on glamourer
> 
> I saw ViviAshe mentioning that the Glamourer's API does not provide the target's design code so I need to manually copy it. But I'm not sure what I need to copy it, where to copy it from and what to do with it.
> 
> Thanks in advance.

Basically, to get it to work in its current state you need to:

- Save the target's snapshot
- Save the target's current glamourer data
- Go to GPose, load the snapshot (you'll turn into a default potato momentarily), apply the glamourer data right after, done.

At the moment the .pmp export isn't working and you'll have no way to go back to your default mods besides restaring the game (afaik).

**Comment by dwnenr** [comment]
@Lucsmat I've tried doing that a few days back but it seems like when you restart the game, the mods on the glamourer design you save no longer works. Is that supposed to be intended (or at least, the current behavior atm)?

**Comment by Lucsmat** [comment]
@dwnenr I'm not sure what you mean by "mods on the glamourer design". Mod data isn't automatically saved in Glamourer designs, you always need to load the snapshot if you want to use them again.

**Comment by dwnenr** [comment]
@Lucsmat After reading your earlier comment, I've tried doing the steps you've mentioned. I've saved the snapshot, also saved their design in glamourer. Go into Gpose, select my name > Load snapshot onto > and navigated to the folder of the person I snapped shot and I just stayed as a lalafell, I did not switch to the person at all. Trying to apply the glamourer data while in this state saves the lalafell and not  the person's data.

**Comment by Lucsmat** [comment]
@dwnenr Your statement of "Trying to apply the glamourer data while in this state saves the lalafell and not the person's data." is very confusing (and may indicate you're doing it wrong). 
If you're applying the already saved glamourer data, you're not saving anything new so it can't possibly overwrite the character data you saved previously with the placeholder lalafell. It is working perflectly fine by following the steps I described, the quoted comment you mentioned is related to fixing the currently 'broken' Snapper so no more workarounds are needed. (Because originally you only needed to save the snapshot)

Going to the steps again: Save the target's snapshot and Save the target's glamourer data (any order) -> enter GPose and load the snapshot -> apply saved glamourer data.

**Comment by dwnenr** [comment]
@Lucsmat Ah, so if I understood it correctly, after loading the snapshot, I also need to apply the design to myself in order to apply the character appearance and clothing saved on the snapshot. And I need to do the same process every time I run the game again.

Although, is it intended that you cant apply any other mods aside from whatever mod the snapshot came with? I've did what you mentioned, save both the snapshot and design, go into gpose and load the snapshot and applied the glamourer  design and I've managed to replicate their appearance, but I couldnt do anything such as changing the outfit they are wearing, skin color, hair etc. or am I doing something wrong here as well?

**Comment by Lucsmat** [comment]
@dwnenr Yes, that is how it works. When you load a snapshot you're basically switching from your mod profile to their mod profile, being limited to what was included in the snapshot. You can change some things about it that you'd be able to with the vanilla Glamourer (such as skin color), but you won't be able to switch to your own mods.

However, if you're familiar with the Snapper file formatting and with modding in general, you can include additional mods in the target's snapshot folder, but that is a bit more advanced. I messed around a bit with it and managed to include animations (but managed to only get the 'raw' ones that do not possess multiple install options to work, songs that came attached to it also didn't play) and even multiple snapshots in a single one (as long as they're from different races it can work without too many conflicts). So do know that some customization can exist, but it becomes more complicated and out of what the mod can do by itself in its current state.

**Comment by dwnenr** [comment]
@Lucsmat Ah, that is a bit unfortunate. I was hoping this would be capable of actually being able to modify the snapshot data to equip my own mods, and even show this to other mare users. Hopefully someone decides to pick this up and expands on this. Thank you very much for the help! Will close this ticket.

**Comment by aftff** [comment]
Hey @dwnenr I know you closed this ticket already but I felt like there were a few pieces of information to add on to this.

Whilst what Lucsmat has said is correct, you can apply the glamour string directly to your character after applying the "broken" snapshot that's not the only way to go about it. This'd require you to keep the string to the side at all times and manually add it every time you want to use the snapshot, not ideal.

In my reply to #5 I added a small python script that can change the formatting so that it'll replace the Glamourer string in there so it applies automatically when you apply a snapshot to a brio character, additionally doing this would also let you create a PMP file like in the old days, I am not 100% certain this'd still work fine (since we're in Dawntrail now) but I also don't see why it'd not work.

Adding your Glamourer string to a snapshot is very straight forward and can be done manually aswell, a bit tedious but not hard in the slightest. (I added a small guide on how to do it manually in my reply to #5) 
If you'd look to add some of your own mods (like dances, other mods, etc) to a snapshot you've taken you should be able to turn it in to a PMP through the snapper menu, (I'd recommend creating a new collection in penumbra for this next step) then enable and set an appropriate priority to that PMP and then make sure that any other mods you want to be prioritized over it to be set as a higher priority than that. 

Hope this helps a bit, happy to answer any more questions you might have.

**Comment by dwnenr** [comment]
Hey @aftff.

I did see your script and your response but I've had a bit of trouble of actually getting the script to run. But regardless, I've tried editing the json file and manually update the glamourer id. But the issue I had was that, I didnt know where to get this id from.

Second, regarding your "applying the mods I want" part, I'm not quite sure how that would work. Let's say for example, I snapshot a person that is wearing chest piece A and pants B. But on my screen, I want them to wear a mod that is on chest piece C and pants D respectively (or even take it off, because maybe C is a full body mod). Even if I set C and D at a higher priority, since the snapshot I took was them wearing A and B, it wouldnt actually reflect the mods I want the character to wear, no?

**Comment by Lucsmat** [comment]
> Hey @dwnenr I know you closed this ticket already but I felt like there were a few pieces of information to add on to this.
> 
> Whilst what Lucsmat has said is correct, you can apply the glamour string directly to your character after applying the "broken" snapshot that's not the only way to go about it. This'd require you to keep the string to the side at all times and manually add it every time you want to use the snapshot, not ideal.
> 
> In my reply to #5 I added a small python script that can change the formatting so that it'll replace the Glamourer string in there so it applies automatically when you apply a snapshot to a brio character, additionally doing this would also let you create a PMP file like in the old days, I am not 100% certain this'd still work fine (since we're in Dawntrail now) but I also don't see why it'd not work.
> 
> Adding your Glamourer string to a snapshot is very straight forward and can be done manually aswell, a bit tedious but not hard in the slightest. (I added a small guide on how to do it manually in my reply to #5) If you'd look to add some of your own mods (like dances, other mods, etc) to a snapshot you've taken you should be able to turn it in to a PMP through the snapper menu, (I'd recommend creating a new collection in penumbra for this next step) then enable and set an appropriate priority to that PMP and then make sure that any other mods you want to be prioritized over it to be set as a higher priority than that.
> 
> Hope this helps a bit, happy to answer any more questions you might have.

I'm aware that could be done, I just didn't mention since re-applying it isn't that troublesome, but since they were struggling with the basic features I didn't go too in-depth on how to do the other stuff, but just letting them know what could or not be done. A simpler way to not have to re-apply the Glamourer data every time you load the snapshop would be simply to save it again after doing it once. The steps would be like this:

Save the target's snapshot and Save the target's glamourer data (any order) -> enter GPose and load the snapshot -> load the saved target's glamourer data on your character - > Save the snapshot (of your own transformed character) once again while in this state (delete/overwrite the original one).

After that you'd be able to make it a one-step process again for the one character, but you'll have to do it for every new one.

About the .pmp, the issue is that the in-game function/button doesn't work. When you try to create the .pmp it asks for a save location but never saves anything. I think you'd be able to create a .pmp with the files manually if you know how to create mods from scratch, but that's something I myself do not know how. Since I've never used the feature before I'm not 100% sure, but I think that used to be the way to incorporate a snapshotted profile to your own mods, by saving this .pmp file and installing in your own mod profile.

**Comment by aftff** [comment]
Hey hey @dwnenr, Python can be a bit tricky to work with if you aren't too familiar with it, if in the future you'd want some additional help getting it to work feel free to reach out, as for the glamourer ID that's just the string that you get when you copy someones character data, similarly to what you'd do for Lucasmat's method. Just go to their character in glamourer, and then at the top you have a "copy the current design to your clipboard." as one of the options. Copy that, then go to the snapshot.json, open it and replace it with the one displayed in the brackets behind "Glamourerstring":"..." where ... would be the existing string.


As for applying your own mods on a snapshot, that'd require you to export the PMP and then import that in to penumbra
I'll @Lucsmat in this as well since they seemed to not be able to get the feature to work. I just tested it out and it worked fine. All I did was that I replaced the string in one of my snapshots, then in the /psnap menu I selected "export snapshot as pmp", then selected the snapshot folder (not the json) that I wanted to use, game froze for a bit and then there was a .pmp file with all the files in my snapper folder. I was never required to select a folder to save it in, only the snapshot I wanted to use and then it saved in my default snapper folder.

Back to what you wanted to do @dwnenr you'd just have to import that pmp file in to your penumbra, set that to the priority you want (below the mods you want to apply over it). 
When I do this I tend to just create a new collection, enable that in there plus all the mods I want to apply to it, then I create a new brio actor and use the collection option under appearance to apply all the mods to the actor (bypassing snapper). I then apply the same glamourer string to that actor (either with a saved design or just copying the string and using the "apply design from clipboard" option.
Then you can just alter any mods that are applied to the character, and anything snapped should be in the pmp modpack you made.

**Comment by Lucsmat** [comment]
Wow, thanks @aftff , it seems like I was under the wrong impression about the feature the whole time. I thought it was supposed to save the loaded in-game snapshot as the .pmp (so I never selected the snapshot folders themselves since I though it was asking for a save location for the loaded snapshot), but turns out it messes directly with the folders. Things just got way easier.

**Comment by dwnenr** [comment]
Hey @aftff, thanks for the explanation but I'm having a bit of trouble following the applying the mod part (3rd paragraph). So basically what you did is save a snapshot, replace the glamourer string with the design string in the json, and exported the snapshot as pmp (I'm asked to select a folder of where to save it, so not sure if I'm doing something wrong here, since you didnt have to even select a folder based on your comment). 

I've loaded the pmp file to penumbra, and in a new collection, I've activated the pmp file and a different set of mod I want to apply. I've set the pmp file as a priority of -1 as most of my mods are a priority of 0 or higher. I've changed the brio actor's collection to the newly created one but I have no clue what you mean with the steps after that (apply appearance, apply glamourer string part). Could you help elaborate that part?

**Comment by aftff** [comment]
Hey @dwnenr The folder its asking you to select is the folder with the snapshot. As far as I know it should always save in your main snapper folder. 

As for priorities, I never used -1 myself so I am not sure if that'd cause any issues but that depends on how penumbra is setup.

As for the appearance/ glamourer string part, what I mean with that is that you'd want to apply the snapshots settings to the brio actor you made (Race, customizations, etc.) which is saved in the glamourer string. You can do that in glamourer if you have saved the person you snapshotted as a design or manually by copying the glamourer string you pasted in the snapshot and manually applying it on the brio actor, it'll be the button next to the copy button in glamourer after you select the brio actor in it.

**Comment by dwnenr** [comment]
@aftff Ah, so I think what you mean is to apply the glamourer string by targeting the brio actor in glamourer and click on the "Try to apply a design from your clipboard". I've managed to spawn the brio actor with the snapshot via this way.

After playing around with the collection a bit, I've realized that I can just set whatever mod I want to apply as a higher priority of the snapshot pmp and just apply that gear via glamourer and they wear the mod no problem. I was under the impression that I had to do somehow modify the snapshop.json file to "reflect" the mods I actually want to use.

A few questions: When spawning the brio actor, I've tried using the "Load snapshot onto" and navigated to the folder that contains the snapshot I want to use. While this does load the snapshot correctly, trying to modify the design to wear anything else does not seem to work. For example, I have bibo enabled at a higher priority and have small clothes set to be NSFW / nude. But removing the chest piece from glamourer seems to break the texture of the skin. I dont think I've made a mistake copying the glamourer id because if I did, I probably wouldnt even see the snapshot correctly applying the design.

However, copying the glamourer id and clicking on the "try to apply a design..." button, I am able to remove their chest piece and see the skin and texture all correctly. Just wanted to ask if the "Load snapshot onto" is not working and the way we have to load a design is to "store" the glamourer id somewhere and manually apply it through glamourer to apply any of my own mods.

**Comment by aftff** [comment]
If I understand how psnap works correctly, when you apply the snapshot to an actor it creates a "fake" collection with all the mods within it and applies that on to the actor, this in turn lets you see all the mods and settings as they were when you saved them. Editing anything on the snapshotted actor would still limit it to any and all information the snapshot had stored at the time, so if you take off the shoes for example, you will see the vanilla FFXIV feet because it didn't actually have any body modifications loaded on that body part.

AFAIK the only way around this is to create the PMP of that snapshot and then toy around with the priorities, you will still run in to slight issues because this was not the intended purpose of snapper, just a possibility and the best solution would always be to get the person in question to show all body parts and outfits that you want to see and then save the snapshot that way. 


Applying the snapshot to yourself will cause everyone to see you as that snapshot, but it will also break your character and force you to relog if you wanted to change any mods or glamourer settings due to the way snapper works, its always recommended to only use brio actors or job pets (people will still see the mods on the job pets so be aware), and if you need more control over things to just apply the collection with the PMP to yourself and turning off your Mare if you dont want others to see how you look. 
Always expect people to be able to see how you see yourself and your pets/minions if you have them on Mare.

**Comment by dwnenr** [comment]
Hmm, weird behavior I am seeing is that my mods dont seem to be applied properly at sometimes. I've managed to get it to apply now. Might have to play around a bit to see what might be causing it. Or maybe it's just a weird edge case / bug. But as you said, the best way is to somehow get them naked and save snapshot of them, so that I can easily apply any mod I want. I might have to test later if I can just manually strip them naked via glamourer and see if that saves the snapshot or not.

Hopefully one day we'll get someone who's nice enough to fix the "applying the snapshot to yourself" breaks your character and you have to close the game and reopen it to fix it. As one of the intentions of using this plugin was to use other people's appearances.

**Comment by aftff** [comment]
I've given all guidance that I can when it comes to the working on this plugin the rest is up to you to troubleshoot yourself.
Also I disagree with your statement that the intention was to use other peoples appearances, it was made to aid with gposing and removing the need to share mcdfs all the time.
